model:
  model_id: audio_rft

  sample_size: 64
  n_layers: 4 
  n_heads: 4
  d_model: 256 #1024

  tokens_per_frame: 64
  rope_impl: simple

  backbone: dit
  causal: true
  uncond: true

  rope_impl: motion
  rope_ats_delta: 2.0

  n_frames: 512 #4096  # change this
  base_fps: 60
  local_window: 4  # 64/60 seconds of ctx
  global_window: 16  # 256/60 seconds of ctx
 
  has_audio: true

  gradient_checkpointing: true
  use_attn_gate: true


train:
  trainer_id: audio_rft
  data_id: audio_dir_loader
  data_kwargs:
    source:
     - /mnt/data/datasets/extracted_tars/kbm/fps/*/*.mp4
    #  - /mnt/data/datasets/extracted_tars/kbm/3ps/*/*.mp4
    #  - /mnt/data/datasets/extracted_tars/kbm/other/*/*.mp4
    target_sampling_rate: 44100
    target_window_length: 22050 # 0.5 second at 44.1kHz

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-15

  # Audio-specific parameters
  sample_rate: 44100
  n_fft_list: [1024, 2048, 512, 256, 128, 64, 32]

  # Audio loss weights
  # loss_weights:
  #   recon: 1.0
  #   stft: 1.0
  #   kl: 1.0e-6
  #   lr_ms_ratio: 0.5  # L/R weight relative to M/S

  # scheduler: LinearWarmup
  # scheduler_kwargs:
  #   warmup_steps: 3000
  #   min_lr: 1.0e-5
  
  ldm_scale: 1.0

  checkpoint_dir: checkpoints/waypoint_1_audio_basic
  resume_ckpt: null

  sample_interval: 500
  save_interval: 5000

wandb:
  name: anm-ol
  project: owl_audio
  run_name: owl-audio-basic