model:
  model_id: audio
  rope_cls: audio
  n_layers: 16
  n_heads: 16
  d_model: 1024
  d_text: 768           # unused, satisfies ModelConfig
  text_encoder: t5-base
  channels: 64        # stable audio VAE latent channels
  patch_size: 1       # over latent frames
  sample_size: [1, 1] # unused, satisfies ModelConfig
  window_length: 10.0
  sample_rate: 25     # audio latent fps
  video_sr: 7.5       # video latent fps
  x0_mode: False
  noise_scale: 1.0
  mlp_ratio: 4
  video_patch_content: 25600  # C*H*W = 32*20*40
  cfg_prob: 0.1

train:
  trainer_id: finevideo
  data_id: finevideo
  data_kwargs:
    source: /workspace/dataset/source/
    window_length: 10.0
    sample_rate: 48000
    video_window_frames: 300
    expected_hw: [20, 40]
    eval_ratio: 0.1
    video_size: [640, 320]  # approx. 360p  
  target_batch_size: 128
  batch_size: 10
  epochs: 1000
  opt: Muon
  opt_kwargs:
    lr: 5.0e-5
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-2
    adamw_eps: 1.0e-8
    adamw_betas: [0.95, 0.95]
    adamw_keys:
      - core.proj_in
      - core.proj_out
      - core.norm_out
      - core.ts_embed
      - core.video_proj
      - .adaln1
      - .adaln2
      - .gate1
      - .gate2
      - .adaln_cross
      - .gate_cross
  checkpoint_dir: checkpoints/vid2audio_baseline-acestep1.5
  resume_ckpt: null
  sample_interval: 200
  save_interval: 5000
  sampler_id: audio_video
  sampling_steps: 50
  cfg_scale: 1.5
  n_samples: 1
  video_vae_id: taehv
  video_vae_ckpt: /workspace/owl-audio-gen/taehv/taehv1_5.pth
  video_fps: 30
  vae_id: ace-step1.5    # audio VAE id

wandb:
  name: its-nmt05
  project: owl-audio-gen
  run_name: audio-ace-step1.5-video